"use client";

import { useEffect, useMemo, useState } from "react";
import { useRouter, useSearchParams } from "next/navigation";
import { ArrowLeft, Building2, FileStack, Loader2, MapPin, Plus, Save, Search, Star, Trash2 } from "lucide-react";

const API_URL = process.env.NEXT_PUBLIC_API_URL || "http://localhost:3333";
type Unidade={id:number;nome:string;cidade:string|null;uf:string|null};
type Preco={id:number;clinicaId:number;procedimentoId:number;valorPaciente:number;valorRepasse:number;ativo:boolean;clinica:{id:number;nome:string;ativo:boolean;unidades:Unidade[]}};
type Procedimento={id:number;nome:string;categoria:string|null;aliases:string[];codigoTuss:string|null;ativo:boolean;precos:Preco[]};
type Item={procedimentoId:number;clinicaId:number|null;unidadeClinicaId:number|null};
type ModeloApi={id:number;nome:string;categoria:string|null;descricao:string|null;ativo:boolean;favorito:boolean;itens:Array<{procedimentoId:number;clinicaId:number|null;unidadeClinicaId:number|null}>};
type OrcamentoOrigem={id:number;codigoPublico:string|null;itens:Array<{procedimentoId:number;clinicaId:number|null;unidadeClinicaId:number|null}>};

function normalizar(v:string){return String(v||"").normalize("NFD").replace(/[\u0300-\u036f]/g,"").toUpperCase().trim();}
function clinicas(p:Procedimento){return (p.precos||[]).filter(x=>x.ativo&&x.clinica?.ativo).sort((a,b)=>a.clinica.nome.localeCompare(b.clinica.nome,"pt-BR"));}

export default function ModeloOrcamentoForm({modeloId}:{modeloId?:number}){
 const router=useRouter(); const searchParams=useSearchParams(); const editando=Number.isInteger(modeloId)&&Number(modeloId)>0;
 const origemParametro=Number(searchParams.get("orcamento"));
 const orcamentoOrigemId=!editando&&Number.isInteger(origemParametro)&&origemParametro>0?origemParametro:undefined;
 const [procedimentos,setProcedimentos]=useState<Procedimento[]>([]); const [nome,setNome]=useState(""); const [categoria,setCategoria]=useState(""); const [descricao,setDescricao]=useState(""); const [ativo,setAtivo]=useState(true); const [favorito,setFavorito]=useState(false); const [itens,setItens]=useState<Item[]>([]); const [busca,setBusca]=useState(""); const [carregando,setCarregando]=useState(true); const [salvando,setSalvando]=useState(false); const [erro,setErro]=useState("");
 useEffect(()=>{void(async()=>{try{setCarregando(true);setErro("");const rp=await fetch(`${API_URL}/procedimentos/catalogo`,{cache:"no-store"});const dp=await rp.json();if(!rp.ok)throw new Error(dp.erro||"Não foi possível carregar procedimentos.");const catalogo:Procedimento[]=Array.isArray(dp)?dp:[];setProcedimentos(catalogo);if(editando){const rm=await fetch(`${API_URL}/modelos-orcamento/${modeloId}`,{cache:"no-store"});const dm:ModeloApi=await rm.json();if(!rm.ok)throw new Error((dm as unknown as {erro?:string}).erro||"Não foi possível carregar o modelo.");setNome(dm.nome);setCategoria(dm.categoria||"");setDescricao(dm.descricao||"");setAtivo(dm.ativo);setFavorito(Boolean(dm.favorito));setItens(dm.itens.map(i=>({procedimentoId:i.procedimentoId,clinicaId:i.clinicaId,unidadeClinicaId:i.unidadeClinicaId})));}else if(orcamentoOrigemId){const ro=await fetch(`${API_URL}/orcamentos/${orcamentoOrigemId}`,{cache:"no-store"});const origem:OrcamentoOrigem=await ro.json();if(!ro.ok)throw new Error((origem as unknown as {erro?:string}).erro||"Não foi possível carregar o orçamento de origem.");setNome(`Modelo ${origem.codigoPublico||`#${origem.id}`}`);setDescricao(`Criado a partir do orçamento ${origem.codigoPublico||`#${origem.id}`}.`);setItens(origem.itens.flatMap(i=>{const p=catalogo.find(x=>x.id===i.procedimentoId&&x.ativo);if(!p)return [];const opcoes=clinicas(p);const c=i.clinicaId?opcoes.find(x=>x.clinicaId===i.clinicaId):undefined;const unidades=c?.clinica.unidades||[];return [{procedimentoId:i.procedimentoId,clinicaId:c?.clinicaId||null,unidadeClinicaId:i.unidadeClinicaId&&unidades.some(u=>u.id===i.unidadeClinicaId)?i.unidadeClinicaId:null}];}));}}catch(e){setErro(e instanceof Error?e.message:"Não foi possível carregar o modelo.");}finally{setCarregando(false);}})();},[editando,modeloId,orcamentoOrigemId]);
 const idsSelecionados=useMemo(()=>new Set(itens.map(i=>i.procedimentoId)),[itens]); const lista=useMemo(()=>{const t=normalizar(busca);return procedimentos.filter(p=>p.ativo&&clinicas(p).length>0&&!idsSelecionados.has(p.id)).filter(p=>!t||normalizar([p.nome,p.categoria||"",p.codigoTuss||"",...(p.aliases||[])].join(" ")).includes(t)).slice(0,12);},[procedimentos,busca,idsSelecionados]);
 function add(p:Procedimento){const cs=clinicas(p);const c=cs.length===1?cs[0]:null;const us=c?.clinica.unidades||[];setItens(a=>[...a,{procedimentoId:p.id,clinicaId:c?.clinicaId||null,unidadeClinicaId:us.length===1?us[0].id:null}]);setBusca("");}
 function alterarClinica(pid:number,cid:number|null){const p=procedimentos.find(x=>x.id===pid);const c=p&&cid?clinicas(p).find(x=>x.clinicaId===cid):null;const us=c?.clinica.unidades||[];setItens(a=>a.map(i=>i.procedimentoId===pid?{...i,clinicaId:cid,unidadeClinicaId:us.length===1?us[0].id:null}:i));}
 async function salvar(){setErro("");if(nome.trim().length<2){setErro("Informe o nome do modelo.");return;}if(itens.length===0){setErro("Adicione ao menos um procedimento.");return;}try{setSalvando(true);const r=await fetch(editando?`${API_URL}/modelos-orcamento/${modeloId}`:`${API_URL}/modelos-orcamento`,{method:editando?"PUT":"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({nome,categoria,descricao,ativo,favorito,itens})});const d=await r.json();if(!r.ok)throw new Error(d.erro||"Não foi possível salvar o modelo.");router.push("/orcamentos/modelos");router.refresh();}catch(e){setErro(e instanceof Error?e.message:"Não foi possível salvar o modelo.");}finally{setSalvando(false);}}
 if(carregando)return <div className="flex min-h-80 items-center justify-center text-xango-muted"><Loader2 size={22} className="mr-2 animate-spin"/>Carregando modelo...</div>;
 return <div className="mx-auto max-w-375 pb-12"><div className="mb-6 flex items-start gap-3"><button onClick={()=>router.push(orcamentoOrigemId?`/orcamentos/${orcamentoOrigemId}`:"/orcamentos/modelos")} className="rounded-md border border-xango-border bg-white p-2 text-xango-primary"><ArrowLeft size={18}/></button><div><h2 className="text-2xl font-semibold text-xango-text">{editando?"Editar modelo":"Novo modelo de orçamento"}</h2><p className="mt-1 text-sm text-xango-muted">{orcamentoOrigemId?"Revise o modelo criado a partir do orçamento. Os preços não são copiados.":"O modelo guarda procedimentos e preferências. Os preços são consultados somente quando o modelo é usado."}</p></div></div>
 {erro&&<div className="mb-5 rounded-lg border border-red-200 bg-red-50 p-3 text-sm font-medium text-red-700">{erro}</div>}
 <div className="grid gap-5 lg:grid-cols-[360px_minmax(0,1fr)]"><div className="space-y-5"><section className="rounded-xl border border-xango-border bg-white p-5"><div className="flex items-center gap-2"><FileStack size={18} className="text-xango-primary"/><h3 className="font-semibold text-xango-text">Identificação</h3></div><label className="mt-4 block text-xs font-semibold text-xango-muted">Nome do modelo</label><input value={nome} onChange={e=>setNome(e.target.value)} maxLength={120} placeholder="Ex.: Check-up básico" className="mt-1 w-full rounded-md border border-xango-border px-3 py-2.5 text-sm outline-none focus:border-xango-primary"/><label className="mt-4 block text-xs font-semibold text-xango-muted">Categoria</label><input value={categoria} onChange={e=>setCategoria(e.target.value)} placeholder="Ex.: Concursos, Preventivo" className="mt-1 w-full rounded-md border border-xango-border px-3 py-2.5 text-sm outline-none focus:border-xango-primary"/><label className="mt-4 block text-xs font-semibold text-xango-muted">Descrição interna</label><textarea value={descricao} onChange={e=>setDescricao(e.target.value)} rows={4} className="mt-1 w-full rounded-md border border-xango-border px-3 py-2.5 text-sm outline-none focus:border-xango-primary"/><div className="mt-4 space-y-3"><label className="flex items-center gap-2 text-sm"><input type="checkbox" checked={ativo} onChange={e=>setAtivo(e.target.checked)} className="accent-xango-primary"/>Modelo ativo</label><label className="flex items-center gap-2 text-sm"><input type="checkbox" checked={favorito} onChange={e=>setFavorito(e.target.checked)} className="accent-xango-primary"/><Star size={15} className={favorito?"fill-amber-400 text-amber-500":"text-xango-muted"}/>Marcar como favorito</label></div></section></div>
 <div className="space-y-5"><section className="rounded-xl border border-xango-border bg-white p-5"><h3 className="font-semibold text-xango-text">Procedimentos do modelo</h3><p className="mt-1 text-xs text-xango-muted">Clínica e unidade são opcionais. Se não definir, o atendente escolhe quando usar o modelo.</p><div className="relative mt-4"><Search size={16} className="absolute left-3 top-1/2 -translate-y-1/2 text-xango-muted"/><input value={busca} onChange={e=>setBusca(e.target.value)} placeholder="Buscar procedimento, sinônimo ou TUSS..." className="w-full rounded-md border border-xango-border py-2.5 pl-9 pr-3 text-sm outline-none focus:border-xango-primary"/></div>{busca&&<div className="mt-2 overflow-hidden rounded-md border border-xango-border">{lista.length===0?<p className="p-3 text-sm text-xango-muted">Nenhum procedimento disponível.</p>:lista.map(p=><button key={p.id} type="button" onClick={()=>add(p)} className="flex w-full items-center justify-between border-b border-xango-border px-3 py-3 text-left last:border-0 hover:bg-xango-background"><span><span className="block text-sm font-semibold text-xango-text">{p.nome}</span><span className="text-xs text-xango-muted">{p.categoria||"Sem categoria"}</span></span><Plus size={16} className="text-xango-primary"/></button>)}</div>}
 <div className="mt-5 space-y-3">{itens.length===0?<div className="rounded-md border border-dashed border-xango-border p-6 text-center text-sm text-xango-muted">Adicione os procedimentos que normalmente fazem parte deste orçamento.</div>:itens.map(item=>{const p=procedimentos.find(x=>x.id===item.procedimentoId);if(!p)return null;const cs=clinicas(p);const c=cs.find(x=>x.clinicaId===item.clinicaId);const us=c?.clinica.unidades||[];return <div key={item.procedimentoId} className="rounded-lg border border-xango-border p-4"><div className="flex items-start justify-between gap-3"><div><p className="font-semibold text-xango-text">{p.nome}</p><p className="mt-1 text-xs text-xango-muted">Preço será consultado ao usar o modelo.</p></div><button type="button" onClick={()=>setItens(a=>a.filter(i=>i.procedimentoId!==item.procedimentoId))} className="rounded-md p-2 text-red-600 hover:bg-red-50"><Trash2 size={16}/></button></div><div className="mt-4 grid gap-3 md:grid-cols-2"><label className="text-xs font-semibold text-xango-muted"><span className="mb-1 flex items-center gap-1"><Building2 size={13}/>Clínica preferencial</span><select value={item.clinicaId||""} onChange={e=>alterarClinica(item.procedimentoId,e.target.value?Number(e.target.value):null)} className="w-full rounded-md border border-xango-border bg-white px-3 py-2.5 text-sm font-normal text-xango-text"><option value="">Definir ao usar</option>{cs.map(x=><option key={x.clinicaId} value={x.clinicaId}>{x.clinica.nome}</option>)}</select></label><label className="text-xs font-semibold text-xango-muted"><span className="mb-1 flex items-center gap-1"><MapPin size={13}/>Unidade preferencial</span><select disabled={!item.clinicaId||us.length===0} value={item.unidadeClinicaId||""} onChange={e=>setItens(a=>a.map(i=>i.procedimentoId===item.procedimentoId?{...i,unidadeClinicaId:e.target.value?Number(e.target.value):null}:i))} className="w-full rounded-md border border-xango-border bg-white px-3 py-2.5 text-sm font-normal text-xango-text disabled:bg-slate-50"><option value="">Definir ao usar</option>{us.map(u=><option key={u.id} value={u.id}>{u.nome}</option>)}</select></label></div></div>})}</div></section>
 <div className="flex justify-end gap-3"><button type="button" onClick={()=>router.push(orcamentoOrigemId?`/orcamentos/${orcamentoOrigemId}`:"/orcamentos/modelos")} className="rounded-md border border-xango-border px-4 py-2.5 text-sm font-semibold text-xango-text">Cancelar</button><button type="button" onClick={()=>void salvar()} disabled={salvando} className="flex items-center gap-2 rounded-md bg-xango-primary px-5 py-2.5 text-sm font-semibold text-white disabled:opacity-50">{salvando?<Loader2 size={16} className="animate-spin"/>:<Save size={16}/>} {salvando?"Salvando...":"Salvar modelo"}</button></div></div></div></div>;
}
